from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any, Iterable

from app.core.config import settings


class ExecutionResult(dict):
    pass


class Executor:
    def __init__(self) -> None:
        settings.generated_dir.mkdir(parents=True, exist_ok=True)

    def execute_plan(
        self,
        plan: Iterable[Any],
        project_name: str | None = None,
        request_text: str | None = None,
    ) -> dict:
        timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        safe_project_name = (project_name or "astra_project").strip().replace(" ", "_")
        output_dir = settings.generated_dir / f"{safe_project_name}_{timestamp}"
        output_dir.mkdir(parents=True, exist_ok=True)

        normalized_steps = list(plan)
        execution_log: list[str] = []
        for index, step in enumerate(normalized_steps, start=1):
            execution_log.append(f"Step {index}: {self._format_step(step)}")

        artifacts: list[str] = []
        lowered_request = (request_text or "").lower()
        if "landing page" in lowered_request or "landing" in lowered_request:
            artifacts.extend(self._create_landing_page_project(output_dir, safe_project_name, request_text or ""))
            execution_log.append("Generated a complete landing page implementation")
        else:
            artifacts.extend(self._create_starter_project(output_dir, safe_project_name))

        readme_path = output_dir / "README.md"
        readme_path.write_text(
            "# ASTRA Generated Project\n\n"
            + "\n".join(f"- {self._format_step(step)}" for step in normalized_steps)
            + "\n\n## Created Files\n"
            + "\n".join(f"- {Path(path).name}" for path in artifacts)
            + "\n",
            encoding="utf-8",
        )
        artifacts.append(str(readme_path))
        execution_log.append(f"Created {len(artifacts)} project files in {output_dir}")

        return {
            "project_path": str(output_dir),
            "artifacts": artifacts,
            "execution_log": execution_log,
        }

    def _create_landing_page_project(self, output_dir: Path, project_name: str, request_text: str) -> list[str]:
        frontend_dir = output_dir / "frontend"
        backend_dir = output_dir / "backend"
        frontend_dir.mkdir(parents=True, exist_ok=True)
        backend_dir.mkdir(parents=True, exist_ok=True)

        index_html = frontend_dir / "index.html"
        styles_css = frontend_dir / "styles.css"
        script_js = frontend_dir / "script.js"
        app_py = backend_dir / "app.py"
        requirements_txt = backend_dir / "requirements.txt"

        title = project_name.replace("_", " ").title()

        index_html.write_text(
            "<!doctype html>\n"
            "<html lang=\"en\">\n"
            "  <head>\n"
            "    <meta charset=\"utf-8\" />\n"
            "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
            f"    <title>{title}</title>\n"
            "    <link rel=\"stylesheet\" href=\"./styles.css\" />\n"
            "  </head>\n"
            "  <body>\n"
            "    <header class=\"nav\">\n"
            f"      <div class=\"brand\">{title}</div>\n"
            "      <nav>\n"
            "        <a href=\"#features\">Features</a>\n"
            "        <a href=\"#pricing\">Pricing</a>\n"
            "        <a href=\"#contact\">Contact</a>\n"
            "      </nav>\n"
            "      <button class=\"btn btn-ghost\">Sign In</button>\n"
            "    </header>\n"
            "\n"
            "    <main>\n"
            "      <section class=\"hero\">\n"
            f"        <p class=\"tag\">Built for: {request_text or 'Modern product teams'}</p>\n"
            f"        <h1>Launch your next project with {title}</h1>\n"
            "        <p class=\"subtitle\">A fast, modern landing page generated by ASTRA and ready to customize.</p>\n"
            "        <div class=\"hero-actions\">\n"
            "          <button class=\"btn btn-primary\" id=\"ctaPrimary\">Get Started</button>\n"
            "          <button class=\"btn btn-secondary\">View Demo</button>\n"
            "        </div>\n"
            "      </section>\n"
            "\n"
            "      <section id=\"features\" class=\"section\">\n"
            "        <h2>Features</h2>\n"
            "        <div class=\"grid\">\n"
            "          <article class=\"card\"><h3>Fast Setup</h3><p>Start in minutes with a clean structure.</p></article>\n"
            "          <article class=\"card\"><h3>Responsive UI</h3><p>Looks great on desktop and mobile.</p></article>\n"
            "          <article class=\"card\"><h3>Easy Customization</h3><p>Swap colors, text, and sections quickly.</p></article>\n"
            "        </div>\n"
            "      </section>\n"
            "\n"
            "      <section id=\"pricing\" class=\"section\">\n"
            "        <h2>Pricing</h2>\n"
            "        <div class=\"pricing\">\n"
            "          <article class=\"plan\"><h3>Starter</h3><p class=\"price\">$0</p><p>For personal projects</p></article>\n"
            "          <article class=\"plan featured\"><h3>Pro</h3><p class=\"price\">$29</p><p>For growing teams</p></article>\n"
            "        </div>\n"
            "      </section>\n"
            "    </main>\n"
            "\n"
            "    <footer id=\"contact\" class=\"footer\">\n"
            "      <p>Need help? Contact support@astra.local</p>\n"
            "      <p id=\"status\"></p>\n"
            "    </footer>\n"
            "\n"
            "    <script src=\"./script.js\"></script>\n"
            "  </body>\n"
            "</html>\n",
            encoding="utf-8",
        )

        styles_css.write_text(
            ":root {\n"
            "  --bg: #0b1220;\n"
            "  --bg-soft: #121d33;\n"
            "  --text: #e5e7eb;\n"
            "  --muted: #9ca3af;\n"
            "  --primary: #22d3ee;\n"
            "  --accent: #38bdf8;\n"
            "}\n\n"
            "* { box-sizing: border-box; }\n"
            "body {\n"
            "  margin: 0;\n"
            "  font-family: Segoe UI, Arial, sans-serif;\n"
            "  color: var(--text);\n"
            "  background: radial-gradient(circle at top left, #1f2937, var(--bg));\n"
            "}\n"
            ".nav {\n"
            "  display: flex;\n"
            "  justify-content: space-between;\n"
            "  align-items: center;\n"
            "  padding: 18px 28px;\n"
            "  border-bottom: 1px solid #1f2a44;\n"
            "}\n"
            ".brand { font-weight: 700; letter-spacing: 0.3px; }\n"
            "nav a { color: var(--muted); margin: 0 10px; text-decoration: none; }\n"
            ".hero { max-width: 920px; margin: 70px auto 20px; padding: 0 20px; text-align: center; }\n"
            ".tag { color: var(--primary); font-weight: 600; }\n"
            "h1 { font-size: clamp(2rem, 5vw, 3.5rem); margin: 12px 0; }\n"
            ".subtitle { color: var(--muted); max-width: 700px; margin: 0 auto; }\n"
            ".hero-actions { margin-top: 28px; display: flex; justify-content: center; gap: 12px; }\n"
            ".btn { border: none; border-radius: 10px; padding: 10px 16px; font-weight: 600; cursor: pointer; }\n"
            ".btn-primary { background: linear-gradient(135deg, var(--primary), var(--accent)); color: #082f49; }\n"
            ".btn-secondary, .btn-ghost { background: #1e293b; color: var(--text); border: 1px solid #334155; }\n"
            ".section { max-width: 980px; margin: 60px auto; padding: 0 20px; }\n"
            ".grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 14px; }\n"
            ".card, .plan { background: var(--bg-soft); border: 1px solid #263146; border-radius: 12px; padding: 18px; }\n"
            ".pricing { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 14px; }\n"
            ".featured { outline: 2px solid var(--primary); }\n"
            ".price { font-size: 1.8rem; margin: 8px 0; }\n"
            ".footer { border-top: 1px solid #1f2a44; padding: 24px; text-align: center; color: var(--muted); }\n",
            encoding="utf-8",
        )

        script_js.write_text(
            "const button = document.getElementById('ctaPrimary');\n"
            "const status = document.getElementById('status');\n"
            "if (button && status) {\n"
            "  button.addEventListener('click', () => {\n"
            "    status.textContent = 'Thanks for your interest. We will contact you shortly.';\n"
            "  });\n"
            "}\n",
            encoding="utf-8",
        )

        app_py.write_text(
            "from fastapi import FastAPI\n\n"
            "app = FastAPI()\n\n"
            "@app.get('/health')\n"
            "def health() -> dict:\n"
            "    return {'status': 'ok'}\n",
            encoding="utf-8",
        )
        requirements_txt.write_text("fastapi\nuvicorn\n", encoding="utf-8")

        return [
            str(index_html),
            str(styles_css),
            str(script_js),
            str(app_py),
            str(requirements_txt),
        ]

    def _create_starter_project(self, output_dir: Path, project_name: str) -> list[str]:
        frontend_dir = output_dir / "frontend"
        backend_dir = output_dir / "backend"
        frontend_dir.mkdir(parents=True, exist_ok=True)
        backend_dir.mkdir(parents=True, exist_ok=True)

        index_html = frontend_dir / "index.html"
        styles_css = frontend_dir / "styles.css"
        script_js = frontend_dir / "script.js"
        app_py = backend_dir / "app.py"
        requirements_txt = backend_dir / "requirements.txt"

        index_html.write_text(
            "<!doctype html>\n"
            "<html lang=\"en\">\n"
            "  <head>\n"
            "    <meta charset=\"utf-8\" />\n"
            "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
            f"    <title>{project_name}</title>\n"
            "    <link rel=\"stylesheet\" href=\"./styles.css\" />\n"
            "  </head>\n"
            "  <body>\n"
            "    <main class=\"container\">\n"
            f"      <h1>{project_name}</h1>\n"
            "      <p>Generated by ASTRA after approval.</p>\n"
            "      <button id=\"actionBtn\">Click me</button>\n"
            "      <p id=\"status\"></p>\n"
            "    </main>\n"
            "    <script src=\"./script.js\"></script>\n"
            "  </body>\n"
            "</html>\n",
            encoding="utf-8",
        )

        styles_css.write_text(
            "body {\n"
            "  margin: 0;\n"
            "  font-family: Segoe UI, Arial, sans-serif;\n"
            "  background: linear-gradient(120deg, #0f172a, #1e293b);\n"
            "  color: #e2e8f0;\n"
            "}\n\n"
            ".container {\n"
            "  max-width: 720px;\n"
            "  margin: 80px auto;\n"
            "  padding: 24px;\n"
            "  border: 1px solid #334155;\n"
            "  border-radius: 12px;\n"
            "  background: rgba(15, 23, 42, 0.6);\n"
            "}\n\n"
            "button {\n"
            "  padding: 10px 14px;\n"
            "  border-radius: 8px;\n"
            "  border: none;\n"
            "  background: #22d3ee;\n"
            "  color: #0f172a;\n"
            "  font-weight: 600;\n"
            "  cursor: pointer;\n"
            "}\n",
            encoding="utf-8",
        )

        script_js.write_text(
            "const btn = document.getElementById('actionBtn');\n"
            "const status = document.getElementById('status');\n"
            "if (btn && status) {\n"
            "  btn.addEventListener('click', () => {\n"
            "    status.textContent = 'ASTRA starter app is running.';\n"
            "  });\n"
            "}\n",
            encoding="utf-8",
        )

        app_py.write_text(
            "from fastapi import FastAPI\n\n"
            "app = FastAPI()\n\n"
            "@app.get('/health')\n"
            "def health() -> dict:\n"
            "    return {'status': 'ok'}\n",
            encoding="utf-8",
        )

        requirements_txt.write_text("fastapi\nuvicorn\n", encoding="utf-8")

        return [
            str(index_html),
            str(styles_css),
            str(script_js),
            str(app_py),
            str(requirements_txt),
        ]

    def write_code_file(self, filename: str, code: str) -> str:
        settings.generated_dir.mkdir(parents=True, exist_ok=True)
        safe_filename = filename.replace("..", "").replace("\\", "/").split("/")[-1]
        target_path = settings.generated_dir / safe_filename
        target_path.write_text(code, encoding="utf-8")
        return str(target_path)

    @staticmethod
    def _format_step(step: Any) -> str:
        if isinstance(step, dict):
            step_number = step.get("step")
            action = step.get("action", "step")
            value = step.get("value", "")
            if value:
                prefix = f"{step_number}. " if step_number is not None else ""
                return f"{prefix}{action}: {value}"
            return f"{step_number}. {action}" if step_number is not None else str(action)

        return str(step)


executor = Executor()


def execute_plan(
    plan: Iterable[Any],
    project_name: str | None = None,
    request_text: str | None = None,
) -> dict:
    return executor.execute_plan(plan, project_name=project_name, request_text=request_text)
